server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://womakersauthdb.mysql.database.azure.com:3306/authdb?serverTimezone=UTC
    username: spring@womakersauthdb
    password: womakers2022!
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: DEBUG
