server:
  port: 9191
spring:
  datasource:
    url: ${DATASOURCE_URL_AUTH}
    username: ${DATASOURCE_USERNAME_AUTH}
    password: ${DATASOURCE_PASSWORD_AUTH}
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: DEBUG
